### PR TITLE
Add expect() function

### PR DESCRIPTION
**Pull request by shadowhand**
Useful when you need to get some values and ensure that all expected
keys are defined.

### CODE REVIEW

**Comment by shadowhand** [comment]
I couldn't think of a better name for this function... I thought about `take()` but that seems like it might be confusing with `grab()`.

**Comment by ameech** [comment]
I'm not sure `ensure` is the best name, but I don't know of a better one. `take()` isn't bad, but I can see that confusion could happen.

Code looks good though!

:+1:

**Comment by shadowhand** [comment]
Maybe `coalese` or `converge`?

**Comment by ameech** [comment]
`expect`?

**Comment by th3fallen** [comment]
`default`(s)?

**Comment by shadowhand** [comment]
@equip/contributors rebased to master and set the new function name to `expect`, as per @ameech's suggestion.

**Pull request merged**
