### PR TITLE
Add take() function

### PR DESCRIPTION
**Pull request by shadowhand**
Makes it easy to get a value that might exist in an array with a
fallback default.

### CODE REVIEW

**Comment by shadowhand** [comment]
@equip/contributors CR please!

**Comment by elazar** [comment]
👍

**Comment by ameech** [comment]
👍

**Comment by sctape** [comment]
👍

**Comment by sctape** [comment]
It'd be awesome if eventually the function could support dot notation to pull from multi-dimensional arrays

**Comment by bvisness** [comment]
It looks like this isn't updated in [README.md](https://github.com/equip/assist/blob/master/README.md) yet.

**Comment by shadowhand** [comment]
@bvisness this has been replaced by [`get`](https://github.com/equip/assist/blob/93739517513d060cb2d447af495c8041cddca5f0/src/array.php#L55), see #10.

**Pull request merged**
