### PR TITLE
Remove pluck() function

### PR DESCRIPTION
**Pull request by shadowhand**
This is the same as array_column() provided by PHP.

### CODE REVIEW

**Comment by shadowhand** [comment]
@equip/contributors CR please.

**Comment by th3fallen** [comment]
damn you're fast.... is this used anywhere in our codebases?

**Comment by elazar** [comment]
Not sure it's exactly the same: `pluck()` always returns an array, `array_column()` does not.

**Comment by shadowhand** [comment]
I doubt it... I am doing a series of changes that will be for version 1.0, so our version locking should be fine.

**Comment by shadowhand** [comment]
@elazar sure it does:

> Returns an array of values representing a single column from the input array.

**Comment by th3fallen** [comment]
array_column always returns an array @elazar ? or did i misread the docs?

**Comment by elazar** [comment]
Ah, I stand corrected. 👍

**Comment by th3fallen** [comment]
👍

**Comment by ameech** [comment]
👍

**Pull request merged**
